"""
Alembic Environment Configuration.

This module configures the Alembic migration environment, setting up
database connections, logging, and target metadata for autogenerated migrations.
It supports both offline and online migration modes.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool

from app.core.database import engine, Base

# Import all models so Alembic can detect them
from app.core.models import User
from app.core.models import Role
from app.core.models import Project
from app.core.models import ProjectTemplate
from app.core.models import ProjectMember
from app.core.models import Task
from app.core.models import TaskType
from app.core.models import UserTaskHistory


# Alembic Config object
config = context.config  # pylint: disable=no-member

# Configure logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set target metadata for autogenerate
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """
    Run migrations in offline mode.
    """
    context.configure(  # pylint: disable=no-member
        url=str(engine.url),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():  # pylint: disable=no-member
        context.run_migrations()  # pylint: disable=no-member


def run_migrations_online() -> None:
    """
    Run migrations in online mode.
    """
    with engine.connect() as connection:
        context.configure(  # pylint: disable=no-member
            connection=connection,
            target_metadata=target_metadata,
        )

        with context.begin_transaction():  # pylint: disable=no-member
            context.run_migrations()  # pylint: disable=no-member


if context.is_offline_mode():  # pylint: disable=no-member
    run_migrations_offline()
else:
    run_migrations_online()
